trigger:
- main

pool:
  name: Default

steps:
- checkout: self

- script: |
    echo ===== ROOT FILES =====
    dir

    echo ===== ALL PACKAGE.JSON FILES =====
    dir /s package.json

    echo ===== ALL VITE FILES =====
    dir /s vite.config.*

    echo ===== ALL SRC FOLDERS =====
    dir /s src
  displayName: Debug Repository Structure